
spring:
  application:
    name: s26871_EntityManager
  banner:
    charset: utf-8
    location: "logo-app"
  datasource:
    url: jdbc:h2:file:./src/main/resources/db
    username: sa
    password: 1234
  h2:
    console:
      path: /my-h2-console
      enabled: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update